apiVersion: apps/v1
kind: Deployment
metadata:
  name: kub-autoscaler-demo
spec:
  selector:
    matchLabels:
      run: kub-autoscaler-demo
  replicas: 1
  template:
    metadata:
      labels:
        run: kub-autoscaler-demo
    spec:
      containers:
      - name: kub-autoscaler-demo
        image: anip95/kub_scaling
        ports:
        - containerPort: 5002
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m